version: '3.8'

services:
  postgres:
    image: postgres:17.4
    container_name: event_publisher_database
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: event_publisher
    ports:
      - "5432:5432"
    volumes:
      - event_publisher_database:/var/lib/postgresql/data
      - ./postgresql.conf:/etc/postgresql/postgresql.conf:ro
    command: ["postgres", "-c", "config_file=/etc/postgresql/postgresql.conf"]

volumes:
  event_publisher_database:
